name = Teachee
description = A simple single column layout demonstrating mobile first and Susy.
preview = preview.png
template = teachee-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/teachee/teachee.layout.css
